#!/usr/bin/env bash

set -exufo pipefail

target="$(realpath "$1")"
dist="$2"
description="$3"

index_files="$(mktemp)"

for arch in all amd64 arm64; do
	dir="$target/dists/$dist/main/binary-$arch"
	mkdir -p "$dir"
	(cd "$target" && dpkg-scanpackages --arch "$arch" pool) > "$dir/Packages"

	size="$(wc -c "$dir/Packages" | awk '{ print $1 }')"
	hash="$(sha256sum "$dir/Packages" | head -c 64)"
	echo " $hash $size main/binary-$arch/Packages" >> "$index_files"
	gzip < "$dir/Packages" > "$dir/Packages.gz"
	rm "$dir/Packages"
	size="$(wc -c "$dir/Packages.gz" | awk '{ print $1 }')"
	hash="$(sha256sum "$dir/Packages.gz" | head -c 64)"
	echo " $hash $size main/binary-$arch/Packages.gz" >> "$index_files"
done

mkdir -p $target/dists/$dist/main/source
echo 'debug ====='
dpkg-scansources "$target/pool"
echo 'debug ====='

dpkg-scansources "$target/pool" > "$target/dists/$dist/main/source/Sources"
size="$(wc -c "$target/dists/$dist/main/source/Sources" | awk '{ print $1 }')"
hash="$(sha256sum "$target/dists/$dist/main/source/Sources" | head -c 64)"
echo " $hash $size main/source/Sources" >> "$index_files"
gzip < "$target/dists/$dist/main/source/Sources" > "$target/dists/$dist/main/source/Sources.gz"
size="$(wc -c "$target/dists/$dist/main/source/Sources.gz" | awk '{ print $1 }')"
hash="$(sha256sum "$target/dists/$dist/main/source/Sources.gz" | head -c 64)"
echo " $hash $size main/source/Sources.gz" >> "$index_files"
rm "$target/dists/$dist/main/source/Sources"

date="$(date -R -u)"

cat << EOF | gpg --clearsign > "$target/dists/$dist/InRelease"
Origin: GardenLinux
Codename: $dist
Description: $description
Components: main
Architectures: all amd64 arm64
Date: $(date -R -u -d "$date")
Valid-Until: $(date -R -u -d "$date + 100 years")
SHA256:
$(cat "$index_files")

EOF

rm "$index_files"
